<?php 
if (!defined('BASEPATH')) exit('No direct script access allowed');

class Mm_search_obj extends CI_Model 
{   //查詢項目設定// 

    function __construct() 
    {   global $_G;
        parent::__construct();
    }
    
    function get_search_info($id=0)
	{	global $_G;
        $final=array(
                's_proj_value'=>array(
          	 			'call_name'=>'專案編號',
             			'type'=>'text'
                    ),
                's_proj_jec_company_id'=>array(
                        'call_name'=>'公司別',
                        'type'=>'select',
						'ld'=>'mm_company_set@def',
						'ld_key'=>'jec_company_id',
						'ld_value'=>'name'               
                    ),
                's_proj_projyear'=>array(
                        'call_name'=>'專案年度',
                        'type'=>'select',
						'ld'=>$this->CM->FormatData(array('key'=>'id','value'=>'name','sn'=>MM_SY,'en'=>(date('Y')+4)),"page_db","num"),
						'ld_key'=>'id',
						'ld_value'=>'name'
                    ),
                's_proj_jec_usersales_id'=>array(
                        'call_name'=>'專案業務',//加單位
                        'type'=>'select',
                        'ld'=>'mm_user_set@def',
                        'ld_value'=>'name',
                        'ld_key'=>'jec_user_id',
                        'full_selected'=>'N'
                    ),
                's_proj_customer_title'=>array(
                        'call_name'=>'客戶名稱-顯示',
                        'type'=>'text',
						'onblur'=>'PL_CloseList();',
						'onclick'=>"PL_ChangePL('cus');",
						'onfocus'=>"PL_ChangePL('cus');",
						'style'=>"width:80px;"
                    ),
                's_proj_jec_customer_id'=>array(
                        'call_name'=>'客戶名稱',
                        'type'=>'hidden'/*,
						'ld'=>'mm_customer_set@def',
						'ld_key'=>'jec_customer_id',
						'ld_value'=>'name'*/
                    ),
                's_proj_salesuser_title'=>array(
                        'call_name'=>'專案負責人/業務-顯示',
                        'type'=>'text',
						'onblur'=>'PL_CloseList();',
						'onclick'=>"PL_ChangePL('user');",
						'onfocus'=>"PL_ChangePL('user');",
						'style'=>"width:80px;"
                    ),
                's_proj_jec_salesuser_id'=>array(
                        'call_name'=>'專案負責人/業務',
                        'type'=>'hidden'
                    ),
                's_proj_name'=>array(
                        'call_name'=>'專案名稱',
                        'type'=>'text'
                    ),
                's_proj_projstatus'=>array(
                        'call_name'=>'專案狀態',
                        'type'=>'select',
						'ld'=>$this->$_G['L_CS']->common_use_ld('projstatus'),
						'ld_key'=>'id',
						'ld_value'=>'name'
                    ),
                's_proj_keyword'=>array(
                        'call_name'=>'關鍵字',
                        'type'=>'text'
                    ),
                's_proj_date'=>array(
                        'call_name'=>'專案日期',
                        'type'=>'text'
                    ),
				's_task_name'=>array(
						'call_name'=>'工作名稱',
						'type'=>'text'
					),
				's_task_tasktype'=>array(
						'call_name'=>'工作狀態',
						'type'=>'select',
						'ld'=>$this->$_G['L_CS']->common_use_ld('tasktype'),
						'ld_key'=>'id',
						'ld_value'=>'name',
						'choose_msg'=>'不限'
					),
				's_task_taskprogress'=>array(
						'call_name'=>'工作進度',
						'type'=>'select',
						'ld'=>array(array('id'=>1,'name'=>'未完成'),array('id'=>2,'name'=>'已完成'),array('id'=>3,'name'=>'已逾期')),
						'ld_key'=>'id',
						'ld_value'=>'name',
						'choose_msg'=>'不限'
					),
				's_task_startdate'=>array(
						'call_name'=>'工作起日',
						'type'=>'text'
					),
				's_task_enddate'=>array(
						'call_name'=>'工作結日',
						'type'=>'text'
					),
                's_task_proj_user_id_title'=>array(
                        'call_name'=>'專案負責人/業務-顯示',
                        'type'=>'text',
						'onblur'=>'PL_CloseList();',
						'onclick'=>"PL_ChangePL('user');",
						'onfocus'=>"PL_ChangePL('user');",
						'style'=>"width:80px;"
                    ),
                's_task_proj_user_id'=>array(
                        'call_name'=>'專案負責人/業務',
                        'type'=>'hidden'
                    ),
                's_task_keyword'=>array(
                        'call_name'=>'關鍵字',
                        'type'=>'text'
                    ),
                's_noticetype'=>array(
                        'call_name'=>'通知狀態',
                        'type'=>'select',
						'ld'=>$this->$_G['L_CS']->common_use_ld('noticetype'),
						'ld_key'=>'id',
						'ld_value'=>'name'
                    ),
                's_startdate'=>array(
                        'call_name'=>'起始日期',
                        'type'=>'text',
						'style'=>'width:100px'
                    ),
                's_enddate'=>array(
                        'call_name'=>'結束日期',
                        'type'=>'text',
						'style'=>'width:100px;'
                    ),
                's_keyword'=>array(
                        'call_name'=>'關鍵字',
                        'type'=>'text'
                    ),
                's_cal_noticetype'=>array(
                        'call_name'=>'日曆的',
                        'type'=>'select',
						'ld'=>$this->$_G['L_CS']->common_use_ld('cal_noticetype'),
						'ld_key'=>'id',
						'ld_value'=>'name'
                    ),
                's_producttemp'=>array(
                        'call_name'=>'範本',
                        'type'=>'select',
						'ld'=>'mm_producttemp_set@def',
						'ld_key'=>'jec_producttemp_id',
						'ld_value'=>'name'
                    ),
				'excel_type'=>array(
						'call_name'=>'excel-type',
						'type'=>'select',
						'ld'=>array(array('id'=>'xls','name'=>'xls'),array('id'=>'xlsx','name'=>'xlsx')),
						'ld_key'=>'id',
						'ld_value'=>'name',
						'full_selected'=>'N',
						'style'=>'width:50px;'
					),
                's_comparetype'=>array(
                        'call_name'=>'',
                        'type'=>'select',
						'ld'=>$this->$_G['L_CS']->common_use_ld('comparetype'),
						'ld_key'=>'id',
						'ld_value'=>'name',
						'full_selected'=>'N'
                    ),
                's_dept_id'=>array(
                        'call_name'=>'',
                        'type'=>'select',
						'ld'=>'mm_dept_set@def',
						'ld_key'=>'jec_dept_id',
						'ld_value'=>'name'
                    ),
                's_user_id_title'=>array(
                        'call_name'=>'人員-顯示',
                        'type'=>'text',
						'onblur'=>'PL_CloseList();',
						'onclick'=>"PL_ChangePL('user');",
						'onfocus'=>"PL_ChangePL('user');",
						'style'=>"width:80px;"
                    ),
                's_user_id'=>array(
                        'call_name'=>'人員',
                        'type'=>'hidden'
                    ),
				's_year'=>array(
						'call_name'=>'年度',
						'type'=>'text',
						'pii'=>array('no'),
						'maxlength'=>4,
						'title'=>'YYYY',
						'style'=>"width:80px;"
					),
				's_string'=>array(
						'call_name'=>'',
						'type'=>'hidden'
					)
            );
     	$final=$id===0?$final:$final[$id];
        return $final;
	}
	
	function get_search_item($tag='')
	{	//
		$info=array(
				'def_proj'=>array('s_proj_value','s_proj_jec_company_id','s_proj_jec_customer_id','s_proj_name','s_proj_projstatus','s_proj_keyword','s_proj_date','s_proj_customer_title','s_proj_jec_salesuser_id','s_proj_salesuser_title'),
				'def_task'=>array('s_proj_value','s_proj_name','s_task_keyword','s_task_name','s_task_tasktype','s_task_taskprogress','s_task_startdate','s_task_enddate','s_task_proj_user_id_title','s_task_proj_user_id'),
				'def_inform'=>array('s_noticetype','s_proj_value','s_proj_name','s_keyword','s_task_name','s_startdate','s_enddate','s_string'),
				'def_cal'=>array('s_cal_noticetype','s_proj_value','s_proj_name','s_keyword','s_task_name','s_startdate','s_enddate'),
				'def_export'=>array('s_producttemp','excel_type'),
				'def_ef_proj'=>array('s_keyword','s_comparetype'),
				'def_ana_work'=>array('s_proj_name','s_proj_jec_customer_id','s_proj_customer_title','s_task_taskprogress','s_task_name','s_task_tasktype','s_dept_id','s_user_id','s_user_id_title'),
				'def_ana_invoice'=>array('s_proj_jec_company_id','s_proj_jec_customer_id','s_proj_name','s_proj_customer_title','s_proj_jec_salesuser_id','s_proj_salesuser_title','s_year','excel_type')
			);
		return isset($info[$tag])?$info[$tag]:array();
	}

    
                                 
}

?>