<?php
	//不要煩我啦><
	$task_data=$this->CM->db->where('jec_task_id',$projt_data['jec_task_id'])->get('jec_task')->result_array();
	//$task_data=$task_data[0];
?>
        	<table class="info-div" cellspacing="1" cellpadding="3">
            	<tr>
            		<td colspan="2" class="info-title">工作項目</td>
            	</tr>
                <tr>
                	<td width="50">工作名稱</td>
                    <td><?=$projt_data['name']?></td>
                </tr>
                <tr>
                	<td>負責人員</td>
                    <td><?=$projt_data['sales_name']?></td>
                </tr>
                <tr>
                	<td>起始日期</td>
                    <td><?=substr($projt_data['startdate'],0,10)?></td>
                </tr>
                <tr>
                	<td>結束日期</td>
                    <td><?=substr($projt_data['enddate'],0,10)?></td>
                </tr>
                <tr>
                	<td>允許延遲</td>
                    <td><?=$projt_data['daydelay']?></td>
                </tr>
                <tr>
                	<td>工作權重</td>
                    <td><?=$projt_data['taskworkweight']?></td>
                </tr>
                <tr>
                	<td>處理原則</td>
                    <td><?=$projt_data['taskprocesstype']?></td>
                </tr>
                <tr>
                	<td>確認方式</td>
                    <td><?=$projt_data['taskconfirmtype']?></td>
                </tr>
                <tr>
                	<td>預估成本</td>
                    <td><?=number_format($projt_data['price'])?></td>
                </tr>
            </table>